In [2]:
import numpy as np
from PIL import Image

In [3]:
img = Image.open("bacEmbedded.png")

In [4]:
pixels = np.array(img)

In [5]:
def to_binary(number):
    byte = []
    if number == 0:
        return '0'
    while number > 0:
        bit = number % 2
        byte.append(str(bit))
        number = number // 2
    byte.reverse()
    return "".join(byte)
        

In [6]:
to_binary(12)

'1100'

In [7]:
pixels.shape

(489, 491)

In [8]:
to_decode = ""
for j in range(0, 491):
    for i in range(0,489):
        to_decode += to_binary(pixels[i][j])[-1]



In [9]:
to_decode

'010110010111010101110000001011000010000001111001011011110111010100100000011001100110100101100111011101010111001001100101011001000010000001101001011101000010000001101111011101010111010000100001001000000010000001001110011011110111011100100000011101000111001001111001001000000110010101101110011000110111001001111001011100000111010001101001011011100110011100100000011110010110111101110101011100100010000001101111011101110110111000100000011011010110010101110011011100110110000101100111011001010010111000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [10]:
all_bytes = [to_decode[i:i+8] for i in range(0, len(to_decode), 8)]
decoded_text = ""
for byte in all_bytes:
    if byte != '00000000':
        decoded_text += chr(int(byte, 2))

In [11]:
decoded_text

'Yup, you figured it out!  Now try encrypting your own message.\x00'

Encoding

In [1]:
binary_message = "0110100001101001001000000111010001101000011001010111001001100101"
##this says "hi there"

In [35]:
pixels

array([[236, 246, 120, ...,  16, 220, 238],
       [ 29,  31,  24, ...,   0,  16,  16],
       [ 22,  24,  30, ...,   0,   0,   0],
       ...,
       [118, 106, 110, ..., 126, 104, 102],
       [137, 140,  82, ...,  80, 122, 138],
       [254, 254, 136, ...,  88, 230, 254]], dtype=uint8)

In [36]:
for i in range(0,489):
    for j in range(0, 491):
        if (pixels[i][j] % 2) != 0:
            pixels[i][j] -= 1

In [37]:
pixels

array([[236, 246, 120, ...,  16, 220, 238],
       [ 28,  30,  24, ...,   0,  16,  16],
       [ 22,  24,  30, ...,   0,   0,   0],
       ...,
       [118, 106, 110, ..., 126, 104, 102],
       [136, 140,  82, ...,  80, 122, 138],
       [254, 254, 136, ...,  88, 230, 254]], dtype=uint8)

In [38]:
index = 0
len_message = len(binary_message)
for j in range(0, 491):
    for i in range(0,489):
        if index < len_message:
            pixels[i][j] = (pixels[i][j] | int(binary_message[index]))
            index += 1

In [39]:
pixels

array([[236, 246, 120, ...,  16, 220, 238],
       [ 29,  30,  24, ...,   0,  16,  16],
       [ 23,  24,  30, ...,   0,   0,   0],
       ...,
       [118, 106, 110, ..., 126, 104, 102],
       [136, 140,  82, ...,  80, 122, 138],
       [254, 254, 136, ...,  88, 230, 254]], dtype=uint8)

In [40]:
to_decode = ""
for j in range(0, 491):
    for i in range(0,489):
        to_decode += to_binary(pixels[i][j])[-1]
all_bytes = [to_decode[i:i+8] for i in range(0, len(to_decode), 8)]
decoded_text = ""
for byte in all_bytes:
    if byte != '00000000':
        decoded_text += chr(int(byte, 2))
decoded_text

'hi there\x00'

In [4]:
import math

In [5]:
def function1(x, y):
    return math.tan(x)-y

In [8]:
def bisection(a, b, e, p):
    rMin = a
    rmax = b
    fRmin = function1(rMin, p)
    rMid = 0.5*(rmax+rMin)
    while (rmax - rMin) > (2*e):
        fRmid = function1(rMid, p)
        if (fRmin*fRmid) < 0:
            rmax = rMid
        else:
            rMin = rMid
            fRmin = fRmid
        rMid = 0.5*(rmax+rMin)
    return rMid

In [11]:
bisection(-((math.pi/2)), math.pi/2, 0.05, 0.5)

0.44178646691106466

In [12]:
bisection(-((math.pi/2)), math.pi/2, 0.05, 0.25)

0.2454369260617026

In [13]:
bisection(-((math.pi/2)), math.pi/2, 0.05, (1/5))

0.2454369260617026

In [14]:
bisection(-((math.pi/2)), math.pi/2, 0.05, 1)

0.8344855486097889

In [15]:
bisection(-((math.pi/2)), math.pi/2, 0.05, math.pi/4)

0.6381360077604268

In [16]:
bisection(-((math.pi/2)), math.pi/2, 0.05, math.pi/2)

1.030835089459151

In [ ]:
bisection(-((math.pi/2)), math.pi/2, 0.005, 0) #not sure why this isnt working

1.5677283652191254